spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/notificacoes}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DATABASE_USER:notificacoes}
spring.datasource.password=${DATABASE_PASSWORD:notificacoes}
spring.h2.console.enabled=false
spring.jpa.hibernate.ddl-auto=update
