apiVersion: v1
kind: Secret
metadata:
  name: biblioteca-secrets
  namespace: biblioteca
type: Opaque
stringData:
  biblioteca-db-user: biblioteca
  biblioteca-db-password: biblioteca
  notificacoes-db-user: notificacoes
  notificacoes-db-password: notificacoes
  rabbitmq-user: biblioteca
  rabbitmq-password: biblioteca
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: biblioteca-config
  namespace: biblioteca
data:
  SPRING_PROFILES_ACTIVE: prod
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  NOTIFICACOES_SERVICE_URL: http://notificacoes-service:8081
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://tempo:4318/v1/traces
  TRACING_SAMPLING_PROBABILITY: "1.0"
