spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/biblioteca}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DATABASE_USER:biblioteca}
spring.datasource.password=${DATABASE_PASSWORD:biblioteca}
spring.h2.console.enabled=false
spring.jpa.hibernate.ddl-auto=update
